FROM ljachym/docker-promnesia:latest
MAINTAINER lukasz <dot> jachym <at> gmail <dot> com

ENV CRON_LOG="/var/log/cron.log"
USER root
RUN apt-get update && apt-get install -y cron sudo
COPY indexer-entrypoint.sh /
RUN chmod 0755 /*.sh
RUN touch ${CRON_LOG} && chmod 0775 ${CRON_LOG} && chown root:${PROMNESIA_USER} ${CRON_LOG}

ENTRYPOINT ["/indexer-entrypoint.sh"]
